#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1
start_service() {
 procd_open_instance
 procd_set_param command /usr/bin/lua /usr/sbin/kwrt-led-slider.lua
 procd_set_param respawn 3600 5 5
 procd_close_instance
}
stop_service() {
 echo none > /sys/class/leds/white:status/trigger
 echo 0 > /sys/class/leds/white:status/brightness
}
